version: "3.3"

services:
  web:
    image: majidlahmidi/apache-php7-d8:1.0
    depends_on:
      - mysql
    ports:
      - 8081:80
    volumes:
      - ./www:/var/www/html
      - ./config/httpd/sites-enabled:/etc/httpd/sites-enabled
    working_dir: /var/www/html
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/database:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_user
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8082:80
    environment:
      - PMA_HOST=mysql